## Numpy Array and Basics
Learn about Numpy Library Basics

In [2]:
import numpy as np

### Creating Array from List

In [3]:
## “NumPy usually works best with arrays of a single data type. Although we can store multiple data types in a NumPy array, it is not good practice because NumPy is optimized for homogeneous (same-type) data.”

## 1 Dimention Array
arr_1d = np.array([1, 2, 3, 4, 5])
print(f"1D Array: {arr_1d}")

# 2 Dimention Array
arr_2d = np.array([[1,2,3,4], [4,5,6,8]]) ## array function always wants single array "array([])" as a parameter then we can make multiple arrays in a single parameter array form making multidimention array
print(f"2D Array: {arr_2d}")

1D Array: [1 2 3 4 5]
2D Array: [[1 2 3 4]
 [4 5 6 8]]


### List Vs Numpy Array

In [4]:
py_list = [1,2,3]
print("Python List: ", py_list*2)  # List duplication (repeats the list)

np_array = np.array([1,2,3,4,5])
print("Numpy Array", np_array*2)  # Element-wise multiplication (each value is multiplied by scalar 2)

# Now we will check that which one is more efficient if we perform element wise multiplication in both list and array
import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("List Operation Time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("Numpy Operation Time: ", time.time() - start) 

Python List:  [1, 2, 3, 1, 2, 3]
Numpy Array [ 2  4  6  8 10]
List Operation Time:  0.26131653785705566
Numpy Operation Time:  0.011747598648071289


### Creating Array from Scratch

In [12]:
zeros = np.zeros((3,4))  # Creates a 3x4 array filled with 0s
print("Zeros Array:\n", zeros)

ones = np.ones((4,3))  # Creates a 4x3 array filled with 1s
print("Ones Array:\n", ones)

# If we want to create an array filled with a specific number, we use np.full()
full = np.full((3,3), 6)  # Creates a 3x3 array filled with 6
print("Full Array:\n", full)

# For creating an array of random numbers between 0 and 1
random = np.random.random((3,4))  # Generates a 3x4 array with random float values in [0, 1)
print("Random Array:\n", random)

# If we want to create a sequence of numbers, we use np.arange()
sequence = np.arange(0,12,2)  # Start=0, Stop=12 (excluded), Step=2
print("Sequence Array:\n", sequence)

Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Full Array:
 [[6 6 6]
 [6 6 6]
 [6 6 6]]
Random Array:
 [[0.65078832 0.7555544  0.84344618 0.48717576]
 [0.97179705 0.81711621 0.09992618 0.88426045]
 [0.58187083 0.00102515 0.70129784 0.24400627]]
Sequence Array:
 [ 0  2  4  6  8 10]


### Vector, Matrices and Tensor

In [29]:
# Vector
vector = np.array([1,2,4,5,3,6])
print("Vector: ", vector)

# Matrix
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix: ", matrix)

# Tensor
tensor = np.array([[[1, 2, 3], [4, 5, 6]],
                   [[7, 8, 9], [10, 11, 12]]])
print("Tensor: ", tensor)

Vector:  [1 2 4 5 3 6]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### Properties of Array

In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape: ", arr.shape)      # Returns the shape (rows, columns) → (2, 3)
print("Dimensions: ", arr.ndim)  # Returns the number of dimensions (axes) → 2
print("Size: ", arr.size)        # Returns total number of elements → 6
print("Data Type: ", arr.dtype)  # Returns the data type of elements → int (or int64 depending on system)

Shape:  (2, 3)
Dimensions:  2
Size:  6
Data Type:  int64


### Array Reshaping

In [27]:
arr = np.arange(12)
print("Original 1D Array:", arr)

# Convert the 1D array into a 2D array using reshape()
reshaped = arr.reshape((3, 4))  # 3 rows, 4 columns
print("\nReshaped Array (3x4):\n", reshaped)

# Convert the multi-dimensional array into a flattened (1D) array
flattened = reshaped.flatten()  # Creates a COPY
flattened[0] = 77  # Modify the flattened array

print("\nFlattened Array (after modification):", flattened)
print("Original Array remains unchanged (because flatten() creates a copy):\n", reshaped)

# Convert to 1D using ravel()
raveled = reshaped.ravel()  # Returns a VIEW (if possible)
print("\nRaveled Array (before modification):", raveled)

raveled[0] = 99  # Modify the raveled array

print("Raveled Array (after modification):", raveled)
print("Original Array may change (because ravel() returns a view when possible):\n", reshaped)

# Transpose the array (rows become columns and columns become rows)
transposed = reshaped.T
print("\nTransposed Array (columns ↔ rows):\n", transposed)

Original 1D Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped Array (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened Array (after modification): [77  1  2  3  4  5  6  7  8  9 10 11]
Original Array remains unchanged (because flatten() creates a copy):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Raveled Array (before modification): [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array (after modification): [99  1  2  3  4  5  6  7  8  9 10 11]
Original Array may change (because ravel() returns a view when possible):
 [[99  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Transposed Array (columns ↔ rows):
 [[99  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
