## Numpy Array Operations

In [2]:
import numpy as np

#### Slicing For 1D Array:

In [3]:
arr = np.arange(11)

print(f"Basic Slicing: {arr[:4]}")
print(f"Basic Slicing: {arr[2:8]}")
print(f"Negative Indexing: {arr[-3]}") # Negative Indexing
print(f"With Step Slicing: {arr[2:7:2]}") # With Step

Basic Slicing: [0 1 2 3]
Basic Slicing: [2 3 4 5 6 7]
Negative Indexing: 8
With Step Slicing: [2 4 6]


#### Slicing for 2D Array

In [4]:
arr_2D = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]]) # 2D Array (2 Axis)


print("Specific Element: ", arr_2D[1,2]) # It is targeting the second element of first row--> Array(row, column)
print("Targeting Entire Row", arr_2D[1]) #It is targeting the entire row of the matrix --> Array(row)
print("Targeting the colume", arr_2D[:,1]) #It is used for targeting the column --> Array(:, column) --> colon is for targeting the entire row

Specific Element:  6
Targeting Entire Row [4 5 6]
Targeting the colume [2 5 8]


### Sorting 

In [5]:
import numpy as np

# Creating a 1D NumPy array with unsorted numbers
unsorted = np.array([3, 1, 2, 6, 4, 9, 0, 10])

# np.sort() returns a new array with elements sorted in ascending order
# Original array remains unchanged
print("Sorted array:", np.sort(unsorted))


# Creating a 2D NumPy array (matrix with rows and columns)
arr_2D = np.array([
    [2, 3, 4],
    [5, 3, 5],
    [9, 2, 10]
])

# axis=0 means sorting column-wise (top to bottom)
# Each column is sorted independently
# Column 1: [2, 5, 9]  -> [2, 5, 9]
# Column 2: [3, 3, 2]  -> [2, 3, 3]
# Column 3: [4, 5, 10] -> [4, 5, 10]
print("Sorted 2D array by column:\n", np.sort(arr_2D, axis=0))


# axis=1 means sorting row-wise (left to right)
# Each row is sorted independently
# Row 1: [2, 3, 4]  -> [2, 3, 4]
# Row 2: [5, 3, 5]  -> [3, 5, 5]
# Row 3: [9, 2, 10] -> [2, 9, 10]
print("Sorted 2D array by row:\n", np.sort(arr_2D, axis=1))

Sorted array: [ 0  1  2  3  4  6  9 10]
Sorted 2D array by column:
 [[ 2  2  4]
 [ 5  3  5]
 [ 9  3 10]]
Sorted 2D array by row:
 [[ 2  3  4]
 [ 3  5  5]
 [ 2  9 10]]


### Filtering 

In [6]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])

even_numbers = numbers[numbers %2==0 ] # Numpy allow us to write Expression in indexing block (Boolean indexing) --> Array[expression OR index]
print("Even Numbers: ", even_numbers)

Even Numbers:  [ 2  4  6  8 10]


### Filter With Mask

In [7]:
mask = numbers % 2 == 0  # Create a Boolean mask for even numbers
print("Even Number with mask Method: ", numbers[mask])  # Use mask to filter values

Even Number with mask Method:  [ 2  4  6  8 10]


### Fancy indexing and np.where()

In [8]:
indices = [0, 2, 4]
print(numbers[indices])  # Returns values present at index positions 0, 2, and 4

where_result = np.where(numbers % 2 == 0)  # Stores indexes of even numbers
print("Print Where Condition: ", where_result)  # Shows the indexes returned by np.where()

print("np Where: ", numbers[where_result])  # Access values using the returned indexes

[1 3 5]
Print Where Condition:  (array([1, 3, 5, 7, 9]),)
np Where:  [ 2  4  6  8 10]


In [9]:
print("Original Array", numbers)

condition_array = np.where(numbers > 5, numbers * 2, numbers * 3)
# np.where(condition, x, y)
# condition: numbers > 5
# if True  -> x = numbers * 2
# if False -> y = numbers * 3

print(condition_array)

# More Explaination
condition_array = np.where(numbers > 5, "true", "false") # np.where(condition, if True, else)
print(condition_array)

Original Array [ 1  2  3  4  5  6  7  8  9 10]
[ 3  6  9 12 15 12 14 16 18 20]
['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


### Adding and Removing Data

In [10]:
arr1 = np.array([1,5,3])
arr2 = np.array([6,5,4])

add = arr1 + arr2 # It will perform addition operation, not used for combining the both of them 
print(add)

combined = np.concatenate((arr1, arr2)) # It will combine the both array
print(combined)

[ 7 10  7]
[1 5 3 6 5 4]


##### Array Compatibility

In [11]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Compatibility Shape: ", a.shape == b.shape == c.shape) # shape is used for checking the number of rows and columns

Compatibility Shape:  True


##### Adding Rows and Columns

In [12]:
original = np.array([[1,2], [2,3]])
new_row = np.array([5,6])

with_new_row = np.vstack((original, new_row)) # np.vstack is always used for adding the row
print("Original: ",original)
print("Adding New Row: ",with_new_row)

new_col = np.array([[7], [8]])
with_new_column = np.hstack((original, new_col)) # np.hstack is always used for adding the column
print("Adding New Column: ",with_new_column)

Original:  [[1 2]
 [2 3]]
Adding New Row:  [[1 2]
 [2 3]
 [5 6]]
Adding New Column:  [[1 2 7]
 [2 3 8]]


##### Deleting Elements

In [13]:
array = np.array([1, 2, 3, 4, 5, 6])
deleted = np.delete(array, [0,3]) # delete elements at index 0 and 3 
deleted_1 = np.delete(array, 2) # delete element at index 2 
print("Array after Deleton: ", deleted)
print("Array_1 after Deleton: ", deleted_1)

Array after Deleton:  [2 3 5 6]
Array_1 after Deleton:  [1 2 4 5 6]


##### Deleting Rows and Columns

In [14]:
# 2D array (matrix): 3 rows × 3 columns
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Original 2D Array: ", array_2d)

# Delete element by index (no axis → array is flattened first)
deleted_flat = np.delete(array_2d, 2)  
# removes element at index 2 after flattening

print(" After delete (no axis - flattened): ", deleted_flat)

# Delete row (axis=0)
deleted_row = np.delete(array_2d, 1, axis=0)  
# axis=0 → removes row at index 1

print(" After delete (axis=0 - row removed):\n", deleted_row)

# Delete column (axis=1)
deleted_col = np.delete(array_2d, 1, axis=1)  
# axis=1 → removes column at index 1

print(" After delete (axis=1 - column removed):\n", deleted_col)

Original 2D Array:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
 After delete (no axis - flattened):  [1 2 4 5 6 7 8 9]
 After delete (axis=0 - row removed):
 [[1 2 3]
 [7 8 9]]
 After delete (axis=1 - column removed):
 [[1 3]
 [4 6]
 [7 9]]
